sudo: required
language: python
python:
    - "2.7"
    - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:juju/stable
  - sudo apt-get update
  - sudo apt-get install juju bzr git
install: pip install tox-travis
script: tox -e lint
